# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 作者信息
author:
  email: shanatos@163.com
  github: wintergl

url: http://shanatos.com # 我的域名
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
category_map: {
  "生活":"a",
  "读书":"b",
  "技术":"c",
  "碎碎念":"d",
  "参考":"e"
}
# 站点信息
title: 知行合一
language: zh-CN
#rss_url: /atom.xml

theme: wixo
#设置自动压缩css
stylus:
  compress: true

deploy:
  type: git
  repo: https://github.com/wintergl/wintergl.github.io.git
  branch: master
